#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib", "$FindBin::Bin/../../plugins", "$FindBin::Bin/../../plugins/lib" }
use Mojolicious::Commands;

# Start commands
Mojolicious::Commands->start_app('MeritCommons');
